### ISSUE TITLE
tpm2_util_esys_handle_to_sys_handle: broken remove or fix

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1817]
The function tpm2_util_esys_handle_to_sys_handle doesnt work. It gets the name and serializes 4 bytes of name as the handle... that doesn't work. Remove or fix.

**Comment by idesai** [comment]
Fixed in f62ed2e3fd41ff56d17d50e9022531bac9eb5472

**Comment by williamcroberts** [comment]
Not fixed, I think we can just delete the code. It's very broken. However, this plays into #1816
